<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Harness.Client\Harness.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Harness.Tests" />
  </ItemGroup>
</Project>
